### ISSUE TITLE
Permissions for colour roles

### ISSUE THREAD

**Issue by kwaggeveld** [DeinAlbtraumTV/ColorBot#1]
Suggestion:
Allow default permissions for colour roles to be changed, such as being mentionable etc.

**Comment by DeinAlbtraumTV** [comment]
I will add this in a future update. However, i don´t plan any major updates like that before Discord has pushed more of the new things for bots, such as the slash commands, as i want to see if i can use some of those to make the bot easier to handle

**Comment by DeinAlbtraumTV** [comment]
Implemented in the latest Update
