### ISSUE TITLE
Colors that are removed when a role is removed.

### ISSUE THREAD

**Issue by chi6814** [DeinAlbtraumTV/ColorBot#2]
Specifically for nitro boosters. If they lose the boost role, they lose their color. There's too many boosters for me to keep track of all of their colors, so having the bot automatically remove would be convenient.

**Comment by DeinAlbtraumTV** [comment]
as in #1 i am currently not planning any big feature updates. However, when i do, i will definetly add this as a feature, probably as well as timed roles

**Comment by DeinAlbtraumTV** [comment]
Implemented in the latest Update
