### ISSUE TITLE
Making it possible for administrators to apply changes/setup the bot

### ISSUE THREAD

**Issue by Lemonpuds** [DeinAlbtraumTV/ColorBot#3]
The person I moderate/admin for on discord leaves most of the work to me as he has limited understanding of how Discord works. Unfortunately this means that I am not the discord owner. This makes setup on the bot impossible. Please consider adding an administrator accessibility function for your bot.

**Comment by DeinAlbtraumTV** [comment]
You should be able to execute all commands needed if you have admin permissions. Could you describe what command isn´t working for you because of your permissions?

**Comment by Lemonpuds** [comment]
Decided to just remove the bot. Thank you though.
